/** @file cmdline.hh
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "Hotspot"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "Hotspot"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char * input_file_arg;	/**< @brief Give a path to an input file containing the sequence (and input structure if known).  */
  char * input_file_orig;	/**< @brief Give a path to an input file containing the sequence (and input structure if known) original value given at command line.  */
  const char *input_file_help; /**< @brief Give a path to an input file containing the sequence (and input structure if known) help description.  */
  char * output_file_arg;	/**< @brief Give a path to an output file which will the sequence, and its structure and energy.  */
  char * output_file_orig;	/**< @brief Give a path to an output file which will the sequence, and its structure and energy original value given at command line.  */
  const char *output_file_help; /**< @brief Give a path to an output file which will the sequence, and its structure and energy help description.  */
  int subopt_arg;	/**< @brief Specify the number of hotspots to output (default is 100) (default='100').  */
  char * subopt_orig;	/**< @brief Specify the number of hotspots to output (default is 100) original value given at command line.  */
  const char *subopt_help; /**< @brief Specify the number of hotspots to output (default is 100) help description.  */
  int turn_arg;	/**< @brief Specify the minimum turn size/ size of hairpin (default is 3) (default='3').  */
  char * turn_orig;	/**< @brief Specify the minimum turn size/ size of hairpin (default is 3) original value given at command line.  */
  const char *turn_help; /**< @brief Specify the minimum turn size/ size of hairpin (default is 3) help description.  */
  int stem_arg;	/**< @brief Specify the minimum number of base pairs in a stem (default is 4) (default='4').  */
  char * stem_orig;	/**< @brief Specify the minimum number of base pairs in a stem (default is 4) original value given at command line.  */
  const char *stem_help; /**< @brief Specify the minimum number of base pairs in a stem (default is 4) help description.  */
  int dangles_arg;	/**< @brief Specify the dangle model to be used (base is 2) (default='2').  */
  char * dangles_orig;	/**< @brief Specify the dangle model to be used (base is 2) original value given at command line.  */
  const char *dangles_help; /**< @brief Specify the dangle model to be used (base is 2) help description.  */
  char * paramFile_arg;	/**< @brief Read energy parameters from paramfile, instead of using the default parameter set..  */
  char * paramFile_orig;	/**< @brief Read energy parameters from paramfile, instead of using the default parameter set. original value given at command line.  */
  const char *paramFile_help; /**< @brief Read energy parameters from paramfile, instead of using the default parameter set. help description.  */
  char * shape_arg;	/**< @brief Give a path to a shape file corresponding to the sequence given.  */
  char * shape_orig;	/**< @brief Give a path to a shape file corresponding to the sequence given original value given at command line.  */
  const char *shape_help; /**< @brief Give a path to a shape file corresponding to the sequence given help description.  */
  int noConv_flag;	/**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA (default=off).  */
  const char *noConv_help; /**< @brief Do not convert DNA into RNA. This will use the Matthews 2004 parameters for DNA help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int input_file_given ;	/**< @brief Whether input-file was given.  */
  unsigned int output_file_given ;	/**< @brief Whether output-file was given.  */
  unsigned int subopt_given ;	/**< @brief Whether subopt was given.  */
  unsigned int turn_given ;	/**< @brief Whether turn was given.  */
  unsigned int stem_given ;	/**< @brief Whether stem was given.  */
  unsigned int dangles_given ;	/**< @brief Whether dangles was given.  */
  unsigned int paramFile_given ;	/**< @brief Whether paramFile was given.  */
  unsigned int shape_given ;	/**< @brief Whether shape was given.  */
  unsigned int noConv_given ;	/**< @brief Whether noConv was given.  */

  char **inputs ; /**< @brief unnamed options (options without names) */
  unsigned inputs_num ; /**< @brief unnamed options number */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *args_info_purpose;
/** @brief the usage string of the program */
extern const char *args_info_usage;
/** @brief the description string of the program */
extern const char *args_info_description;
/** @brief all the lines making the help output */
extern const char *args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct args_info *args_info);
/**
 * Deallocates the string fields of the args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
